site_name: "Projeto Final Engenharia de Dados"
theme:
  name: ivory
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
nav:
  - Home: index.md
  - Projeto: projeto.md
  - Configuração: configuracao.md
  - Pipeline: pipeline.md
  #- Passo a Passo: step.md
  